### ISSUE TITLE
Media not found even when there is media

### ISSUE THREAD

**Issue by fpcarva** [Minyall/gephi_twitter_media_downloader#12]
Hello, using the repository, I found an error. When the id contains a link or contains more than one image it cannot identify the media. Examples of id: '1294252270218088449',
'1294252332197261312', or '1294859797817364481'. Thank you very much

**Comment by Minyall** [comment]
I've had my suspicions about this. I'm tied up next week but I'll take a look when I get back. May need some digging for a fix. Thanks for the ids. That will help.

**Comment by Minyall** [comment]
Ok, I had some time this evening so I took a look. I think this is now fixed 832f38cac4aef268ddbe52d4daa58eba00f20690. You'll need to redownload the repository and try with the new version.

**Comment by fpcarva** [comment]
> Ok, I had some time this evening so I took a look. I think this is now fixed [832f38c](https://github.com/Minyall/gephi_twitter_media_downloader/commit/832f38cac4aef268ddbe52d4daa58eba00f20690). You'll need to redownload the repository and try with the new version.

Oh, thank you very much. I downloaded it and it worked. I'm going to make a lot of use of it this week, anything I report. But thank you very much, really
